### ISSUE TITLE
Brainfuck Interpreter

### ISSUE THREAD

**Issue by DiamondCoder1000** [Raven-Development-Inc/Universal-Computer-Operating-System#1]

**Comment by DiamondCoder1000** [comment]
Done

**Comment by emm312** [comment]
bro loops still don't work

**Comment by DiamondCoder1000** [comment]
It dies now

**Comment by DiamondCoder1000** [comment]
Does*

**Comment by DiamondCoder1000** [comment]
Im bad

**Comment by DiamondCoder1000** [comment]
Arent loops done?

**Comment by emm312** [comment]
nope, they are broken

**Comment by DiamondCoder1000** [comment]
Shit, thats exactly what you did lmao nvm

**Comment by emm312** [comment]
also another problem:
my code does
do { }
while ()
ie. it executes the code then checks the condition
if the cell was 0 before the loop starts, it would still execute it which is wrong

**Comment by DiamondCoder1000** [comment]
the flag
isLoop
so like the code checks it every time it hits the .endLoop subroutine/label
so it doesn't execute if it's false

**Comment by emm312** [comment]
? no that's not the problem

**Comment by emm312** [comment]
i have an idea on how to fix it though

**Comment by DiamondCoder1000** [comment]
O, ok

**Comment by emm312** [comment]
never mind it will be too slow

**Comment by DiamondCoder1000** [comment]
Slow? Well you can clock this to more than 1 mhz

**Comment by emm312** [comment]
even a couple extra instructions can make a massive difference in speed

**Comment by DiamondCoder1000** [comment]
Complex instructions?
